---
apiVersion: v1
kind: Secret
metadata:
  name: gracehoppeh-gracehoppeh-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/gracehoppeh-backend-gitops
